PSD.Web/Areas/BenefitPrograms/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PSD.Model;
using PSD.Security;

namespace PSD.Web.Areas.BenefitPrograms.Controllers
{
    public class CouponController : PSD.Web.Controllers._BaseWebController
    {
        private Controller.BenefitPrograms.Coupon.CouponController controller;
        public CouponController()
            : base("CouponController")
        {
            controller = new Controller.BenefitPrograms.Coupon.CouponController(Configurations);
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

PSD.Web/Areas/BenefitProgramsManagement/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PSD.Model;
using PSD.Security;
using PSD.Web.Areas.BenefitProgramsManagement.Models;

namespace PSD.Web.Areas.BenefitProgramsManagement.Controllers
{
    [Authorization(allowedRoles: Controller.UserRole.AppAdmin)]
    public class CouponController : PSD.Web.Controllers._BaseWebController
    {
        private Controller.BenefitPrograms.Coupon.CouponManagementController controller;
        public CouponController()
            : base("CouponController")
        {
            controller = new Controller.BenefitPrograms.Coupon.CouponManagementController(Configurations);
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DiscountsDetail()
        {
            return View(Configurations.BenefitProgram_Coupon_Discount);
        }
        public ActionResult DiscountsEdit()
        {
            if (!Configurations.BenefitProgram_Coupon_IsOpen || (!Configurations.BenefitProgram_Coupon_S1_IsOpen && !Configurations.BenefitProgram_Coupon_S2_IsOpen))
            {
                NotifyUser(messageError: "Ha concluido la temporada de captura de compras");
                return RedirectToAction("DiscountsDetail");
            }

            return View(Configurations.BenefitProgram_Coupon_Discount);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DiscountsEdit(string[][] model)
        {
            if (model == null)
            {
                NotifyUser(messageDebug: controllerTraceId + "DistributorCreate[Post].111 No model was received");
                return RedirectToAction("DiscountsDetail");
            }

            int[,] auxModel = new int[10,5];
            for (int a = 0; a < 10; a++)
            {
                for (int b = 0; b < 5; b++)
                {
                    try { auxModel[a, b] = Convert.ToInt32(model[a][b]); }
                    catch { auxModel[a, b] = 0; }
                }
            }

            if (controller.DiscountsUpdate(auxModel) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("DiscountsDetail");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return View(Configurations.BenefitProgram_Coupon_Discount);
        }
        public ActionResult PromotionsDetail()
        {
            return View(Configurations.BenefitProgram_Coupon_Promotion);
        }
        public ActionResult PromotionsEdit()
        {
            if (!Configurations.BenefitProgram_Coupon_IsOpen || (!Configurations.BenefitProgram_Coupon_S1_IsOpen && !Configurations.BenefitProgram_Coupon_S2_IsOpen))
            {
                NotifyUser(messageError: "Ha concluido la temporada de captura de compras");
                return RedirectToAction("DiscountsDetail");
            }

            return View(Configurations.BenefitProgram_Coupon_Promotion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PromotionsEdit(string[][] model)
        {
            if (model == null)
            {
                NotifyUser(messageDebug: controllerTraceId + "DistributorCreate[Post].111 No model was received");
                RedirectToAction("PromotionsDetail");
            }

            int[,] auxModel = new int[12, 2];
            for (int a = 0; a < 12; a++)
            {
                for (int b = 0; b < 2; b++)
                {
                    try { auxModel[a, b] = Convert.ToInt32(model[a][b]); }
                    catch { auxModel[a, b] = 0; }
                }
            }

            if (controller.PromotionsUpdate(auxModel) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("PromotionsDetail");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return View(Configurations.BenefitProgram_Coupon_Promotion);
        }

        public ActionResult CouponConfigurations()
        {
            CouponConfigurationsModel model = new CouponConfigurationsModel();
            model.IsOpen = Configurations.BenefitProgram_Coupon_IsOpen;
            model.S1IsOpen = Configurations.BenefitProgram_Coupon_S1_IsOpen;
            model.S2IsOpen = Configurations.BenefitProgram_Coupon_S2_IsOpen;
            model.IsCalculated = Configurations.BenefitProgram_Coupon_IsCalculated;
            model.S1IsCalculated = Configurations.BenefitProgram_Coupon_S1_IsCalculated;
            model.S2IsCalculated = Configurations.BenefitProgram_Coupon_S2_IsCalculated;
            return View(model);
        }
        public ActionResult CouponConfigurations_S1IsOpen_TurnOff()
        {

            if (controller.S1IsOpen_TurnOff() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponConfigurations");
        }
        public ActionResult CouponConfigurations_S1IsOpen_TurnOn()
        {

            if (controller.S1IsOpen_TurnOn() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponConfigurations");
        }
        public ActionResult CouponConfigurations_S2IsOpen_TurnOff()
        {

            if (controller.S2IsOpen_TurnOff() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponConfigurations");
        }
        public ActionResult CouponConfigurations_S2IsOpen_TurnOn()
        {

            if (controller.S2IsOpen_TurnOn() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponConfigurations");
        }


        public ActionResult CouponProcessing()
        {
            CouponConfigurationsModel model = new CouponConfigurationsModel();
            model.IsOpen = Configurations.BenefitProgram_Coupon_IsOpen;
            model.S1IsOpen = Configurations.BenefitProgram_Coupon_S1_IsOpen;
            model.S2IsOpen = Configurations.BenefitProgram_Coupon_S2_IsOpen;
            model.IsCalculated = Configurations.BenefitProgram_Coupon_IsCalculated;
            model.S1IsCalculated = Configurations.BenefitProgram_Coupon_S1_IsCalculated;
            model.S2IsCalculated = Configurations.BenefitProgram_Coupon_S2_IsCalculated;
            return View(model);
        }

        public ActionResult CouponProcessing_ProcessS1()
        {
            if (controller.ProcessS1() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponProcessing");
        }
        public ActionResult CouponProcessing_ProcessS2()
        {
            if (controller.ProcessS2() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponProcessing");
        }

        public ActionResult CouponProcessing_ReportS1()
        {
            List<ContractSubdistributor> currentContracts = controller.RetrieveActiveContracts();
            if (currentContracts.Count > 0 && controller.ResultManager.IsCorrect)
            {
                return View(currentContracts);
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponProcessing");
        }

        public ActionResult CouponProcessing_ReportS2()
        {
            List<ContractSubdistributor> currentContracts = controller.RetrieveActiveContracts();
            if (currentContracts.Count > 0 && controller.ResultManager.IsCorrect)
            {
                return View(currentContracts);
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponProcessing");
        }
        public ActionResult CouponProcessing_Restart()
        {
            if (controller.StartNewCycle() && controller.ResultManager.IsCorrect)
            {
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("CouponProcessing");
        }

    }
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/CouponConfigurations.cshtml
@using PSD.Security
@model PSD.Web.Areas.BenefitProgramsManagement.Models.CouponConfigurationsModel
@{
    ViewBag.Title = "Configuraciones";
}

<div class="form-group">
    <label for="" class="col-md-2 control-label">Ciclo abierto<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-10">
        <label class="checkbox-inline">
            <input type="checkbox" data-toggle="toggle" data-onstyle="default" @(Model.IsOpen ? "checked" : "") disabled>
        </label>
        <span class="input-group-sm text-muted">Mientras esta activo, los convenios del año estar&aacute;n activos. Esta configuraci&oacute;n pasa de encendido a apagado cuando se procesan los cupones del a&ntilde;o en curso.</span>
    </div>
</div>
<div class="form-group">&nbsp;</div>
<div class="form-group">
    <label for="" class="col-md-2 control-label">Semestre 1 <span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-10">
        <label class="checkbox-inline">
            <input type="checkbox" id="S1IsOpen" data-toggle="toggle" @(Model.S1IsOpen ? "checked" : "") @(Model.IsOpen & !Model.S1IsCalculated ? "" : "disabled")>
        </label>
        <span class="input-group-sm text-muted">Mientras esta activo, los distribuidores podr&aacute;n registrar y editar las compras de sus participantes para el primer semestre.</span>
    </div>
</div>
<div class="form-group">&nbsp;</div>
<div class="form-group">
    <label for="" class="col-md-2 control-label">Semestre 2 <span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-10">
        <input type="checkbox" id="S2IsOpen" data-toggle="toggle" @(Model.S2IsOpen ? "checked" : "") @(Model.IsOpen & !Model.S2IsCalculated ? "" : "disabled")>
        <span class="input-group-sm text-muted">Mientras esta activo, los distribuidores podr&aacute;n registrar y editar las compras de sus participantes para el segundo semestre.</span>
    </div>
</div>

@section pageCSS{
}
@section pageScripts{
    <link href="/Content/Components/ToggleCheckbox/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="/Content/Components/ToggleCheckbox/bootstrap-toggle.min.js"></script>
    <script>
        $(function () {
            $('#S1IsOpen').change(function () {
                window.location.href = '/BenefitProgramsManagement/Coupon/@(Model.S1IsOpen ? "CouponConfigurations_S1IsOpen_TurnOff" : "CouponConfigurations_S1IsOpen_TurnOn")';
            });
            $('#S2IsOpen').change(function () {
                window.location.href = '/BenefitProgramsManagement/Coupon/@(Model.S2IsOpen ? "CouponConfigurations_S2IsOpen_TurnOff" : "CouponConfigurations_S2IsOpen_TurnOn")';
            });
        })
    </script>
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/CouponProcessing.cshtml
@using PSD.Security
@model PSD.Web.Areas.BenefitProgramsManagement.Models.CouponConfigurationsModel
@{
    ViewBag.Title = "Procesamiento de cupones";
}

<div class="form-group">
    <label for="" class="col-md-2 control-label">Estado del ciclo<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-8">
        @if (Model.IsCalculated)
        {
            <label>Procesado</label>
            <button type="button" class="btn btn-primary" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/CouponProcessing_Restart';">Comenzar nuevo ciclo</button>
            <span class="input-group-sm text-muted"></span>
        }
        else
        {
            <label>Activo</label>
            <span class="input-group-sm text-muted">al procesar el ambos semestres, se podrá generar el reporte de cupones, sin embargo ya no se podrán registrar más compras</span>
        }
    </div>
</div>
<div class="form-group"><div class="col-md-12">&nbsp;</div></div>
<div class="form-group">
    <label for="" class="col-md-2 control-label">Semestre 1<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-8">
        @if (Model.S1IsCalculated)
        {
            <label>Procesado</label>
            <button type="button" class="btn btn-success" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/CouponProcessing_ReportS1';">Ver reporte de cupones</button>
            <span class="input-group-sm text-muted"></span>
        }
        else
        {
            <label>Por procesar</label>
            <button type="button" class="btn btn-warning" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/CouponProcessing_ProcessS1';">Procesar</button>
            <span class="input-group-sm text-muted">al procesar el semestre 1, se podrá generar el reporte de cupones, sin embargo ya no se podrán registrar más compras para el semestre</span>
        }
    </div>
</div>
<div class="form-group"><div class="col-md-12">&nbsp;</div></div>
<div class="form-group">
    <label for="" class="col-md-2 control-label">Semestre 2<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
    <div class="col-md-8">
        @if (Model.S2IsCalculated)
        {
            <label>Procesado</label>
            <button type="button" class="btn btn-success" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/CouponProcessing_ReportS2';">Ver reporte de cupones</button>
            <span class="input-group-sm text-muted"></span>
        }
        else
        {
            <label>Por procesar</label>
            <button type="button" class="btn btn-warning" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/CouponProcessing_ProcessS2';">Procesar</button>
            <span class="input-group-sm text-muted">al procesar el semestre 2, se podrá generar el reporte de cupones, sin embargo ya no se podrán registrar más compras para el semestre</span>
        }
    </div>
</div>

@section pageCSS{
}
@section pageScripts{
    <script>
        $(function () {
        });
    </script>
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/CouponProcessing_ReportS1.cshtml
@using PSD.Security
@using PSD.Controller
@using PSD.Model
@model List<ContractSubdistributor>

@{
    ViewBag.Title = "Reporte de cupones";
    ViewBag.SubTitle = "Semestre 1";
}

<div class="col-md-12 text-right">
    @if (Identity.CurrentUser.IsInRole(UserRole.AppAdmin))
    {
        <a class="btn-export" href="#"><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Exportar </a>
    }
</div>
<div class="col-md-12">
    <table class="table datatable table-export">
        <thead>
            <tr>
                <th>Id Convenio</th>
                <th>Subdistribuidor/Agricultor</th>
                <!--<th>Periodo</th>
                <th>Regi&oacute;n asignada</th>
                <th>Zona asignada</th>-->
                <th>Meta total</th>
                <th>Meta S1</th>
                <th>%alcanzado</th>
                <th>%alcanzado S1</th>
                <th>$comprado S1</th>
                <th>Cup&oacute;n descuento</th>
                <th>Cup&oacute;n descuento por distribuidor</th>
                <th>Cup&oacute;n promoci&oacute;n</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ContractSubdistributor item in Model)
            {
                <tr>
                    <td><a href="/Contracts/ToSubdistributor/Detail/@item.Id">@item.IdB</a></td>
                    <td>@item.Subdistributor.DisplayName</td>
                    <!--<td>@item.Year</td>
                    <td>@item.RegisteredRegionName</td>
                    <td>@item.RegisteredZoneName</td>-->
                    <td>@PSD.Common.Strings.FormatCurrency(item.AmountGoalTotal)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.AmountGoalS1)</td>
                    <td>@PSD.Common.Strings.FormatPercentage(item.GoalTotalPercentage)</td>
                    <td>@PSD.Common.Strings.FormatPercentage(item.GoalTotalS1Percentage)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.PurchaseTotalS1)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.SubdistributorDiscountCoupon.CouponAmountS1)</td>
                    <td>
                        @foreach (DistributorPurchasesXContractSubdistributor itemDistributor in item.DistributorPurchases)
                        {
                            <span>@itemDistributor.Distributor.DisplayName (@PSD.Common.Strings.FormatPercentage(itemDistributor.CouponSharePercentageS1) = @PSD.Common.Strings.FormatCurrency(itemDistributor.CouponShareAmountS1))</span>
                        }
                    </td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.SubdistributorPromotionCoupon.CouponAmountS1)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section pageCSS{
}
@section pageScripts{
    <script src="/Content/Components/Table2Excel/tableExport.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.btn-export').on('click', function () {
                $('.table-export').tableExport({ type: 'excel' });//csv
            });
        });
    </script>
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/CouponProcessing_ReportS2.cshtml
@using PSD.Security
@using PSD.Controller
@using PSD.Model
@model List<ContractSubdistributor>

@{
    ViewBag.Title = "Reporte de cupones";
    ViewBag.SubTitle = "Semestre 2";
}

<div class="col-md-12 text-right">
    @if (Identity.CurrentUser.IsInRole(UserRole.AppAdmin))
    {
        <a class="btn-export" href="#"><span class="glyphicon glyphicon-save" aria-hidden="true"></span> Exportar </a>
    }
</div>
<div class="col-md-12">
    <table class="table datatable table-export">
        <thead>
            <tr>
                <th>Id Convenio</th>
                <th>Subdistribuidor/Agricultor</th>
                <!--<th>Periodo</th>
                <th>Regi&oacute;n asignada</th>
                <th>Zona asignada</th>-->
                <th>Meta</th>
                <th>Meta S2</th>
                <th>$comprado S2</th>
                <th>%alcanzado</th>
                <th>%alcanzado S2</th>
                <th>Cup&oacute;n descuento</th>
                <th>Cup&oacute;n descuento por distribuidor</th>
                <th>Cup&oacute;n promoci&oacute;n</th>
            </tr>
        </thead>
        <tbody>
            @foreach (ContractSubdistributor item in Model)
            {
                <tr>
                    <td><a href="/Contracts/ToSubdistributor/Detail/@item.Id">@item.IdB</a></td>
                    <td>@item.Subdistributor.DisplayName</td>
                    <!--<td>@item.Year</td>
                    <td>@item.RegisteredRegionName</td>
                    <td>@item.RegisteredZoneName</td>-->
                    <td>@PSD.Common.Strings.FormatCurrency(item.AmountGoalTotal)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.AmountGoalS2)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.PurchaseTotalS2)</td>
                    <td>@PSD.Common.Strings.FormatPercentage(item.GoalTotalPercentage)</td>
                    <td>@PSD.Common.Strings.FormatPercentage(item.GoalTotalS2Percentage)</td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.SubdistributorDiscountCoupon.CouponAmountS2)</td>
                    <td>
                        @foreach(DistributorPurchasesXContractSubdistributor itemDistributor in item.DistributorPurchases)
                        {
                            <span>@itemDistributor.Distributor.DisplayName (@PSD.Common.Strings.FormatPercentage(itemDistributor.CouponSharePercentageS2) = @PSD.Common.Strings.FormatCurrency(itemDistributor.CouponShareAmountS2))</span>
                        }
                    </td>
                    <td>@PSD.Common.Strings.FormatCurrency(item.SubdistributorPromotionCoupon.CouponAmountS2)</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section pageCSS{
}
@section pageScripts{
    <script src="/Content/Components/Table2Excel/tableExport.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('.btn-export').on('click', function () {
                $('.table-export').tableExport({ type: 'excel' });//csv
            });
        });
    </script>
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/DiscountsEdit.cshtml
@using PSD.Security
@using PSD.Model
@using PSD.Controller
@using PSD.Common
@model int[,]
@{
    ViewBag.Title = "Editar Tabla de Descuentos";
}

@using (Html.BeginForm("DiscountsEdit", "Coupon", new { }, FormMethod.Post, new { @class = "form-horizontal col-md-12", role = "form", onsubmit = "return ValidateForm()", name = "DiscountsEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group col-md-8">
        <!--<label for="" class="col-md-4 control-label">label <span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>-->
        <table class="table table-bordered text-right">
            <thead>
                <tr>
                    <th class="text-center">Limite inferior (&gt;=)</th>
                    <th class="text-center">Limite superior (&lt;)</th>
                    <th class="text-center">=</th>
                    <th class="text-center">%Cupón (Antigüedad 0@*PSD.Common.Dates.Today.Year*@)</th>
                    <th class="text-center">%Cupón (Antigüedad 1@*(PSD.Common.Dates.Today.Year - 1)*@)</th>
                    <th class="text-center">%Cupón (Antigüedad 2@*(PSD.Common.Dates.Today.Year - 2)*@)</th>
                </tr>
            </thead>
            @for (int a = 0; a < 10; a++)
            {
                <tr>
                    @for (int b = 0; b < 5; b++)
                    {
                        if (b == 2)
                        {
                            <td></td>
                        }
                        <td>
                            <div class="input-group">
                                <input type="text" class="form-control" name="model[@a][@b]" id="model[@a][@b]" value="@Model[a, b]" placeholder="" />
                                <span class="input-group-addon">%</span>
                            </div>
                        </td>
                    }
                </tr>
            }            
        </table>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            @Html.ValidationSummary()
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-default" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/DiscountsDetail';">Cancelar</button>
        </div>
    </div>
}
@section pageCSS{
}
@section pageScripts{
    <script type="text/javascript">
        function ValidateForm() {
            return true;
        }
    </script>
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/Index.cshtml
@{
    ViewBag.Title = "Cupones";
}

PSD.Web/Areas/BenefitProgramsManagement/Views/Coupon/PromotionsEdit.cshtml
@using PSD.Security
@using PSD.Model
@using PSD.Controller
@using PSD.Common
@model int[,]
@{
    ViewBag.Title = "Tabla de Promociones";
    int currentMonth = 3; // ¿PSD.Common.Dates.Today.Month;
}

@using (Html.BeginForm("PromotionsEdit", "Coupon", new { }, FormMethod.Post, new { @class = "form-horizontal col-md-12", role = "form", onsubmit = "return ValidateForm()", name = "PromotionsEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <!--<label for="" class="col-md-4 control-label">label <span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>-->
        <table class="table table-bordered text-right">
            <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Enero</th>
                    <th class="text-center">Febrero</th>
                    <th class="text-center">Marzo</th>
                    <th class="text-center">Abril</th>
                    <th class="text-center">Mayo</th>
                    <th class="text-center">Junio</th>
                </tr>
            </thead>
            @for (int a = 0; a < 2; a++)
            {    
                <tr>
                    <td><span>@(a == 0 ? "Porcentaje" : "Monto mínimo de compra")</span></td>
                    @for (int b = 0; b < 6; b++)
                    {
                        <td>
                            <div class="input-group">
                                @if (a == 0)
                                {
                                    <input type="text" class="form-control" name="model[@b][@a]" id="model[@b][@a]" value="@Model[b, a]" placeholder="" @(b < currentMonth ? "readonly" : "") />
                                    <span class="input-group-addon">%</span>
                                }
                                else
                                {
                                    <span class="input-group-addon">$</span>
                                    <input type="text" class="form-control" name="model[@b][@a]" id="model[@b][@a]" value="@Model[b, a]" placeholder="" @(b < currentMonth ? "readonly" : "") />
                                }
                            </div>
                        </td>
                    }
                </tr>
            }
        </table>
        <table class="table table-bordered text-right">
            <thead>
                <tr>
                    <th class="text-center"></th>
                    <th class="text-center">Julio</th>
                    <th class="text-center">Agosto</th>
                    <th class="text-center">Septiembre</th>
                    <th class="text-center">Octubre</th>
                    <th class="text-center">Noviembre</th>
                    <th class="text-center">Diciembre</th>
                </tr>
            </thead>
            @for (int a = 0; a < 2; a++)
            {
                <tr>
                    <td><span>@(a == 0 ? "Porcentaje" : "Monto mínimo de compra")</span></td>
                    @for (int b = 6; b < 12; b++)
                    {
                        <td>
                            <div class="input-group">
                                @if (a == 0)
                                {
                                    <input type="text" class="form-control" name="model[@b][@a]" id="model[@b][@a]" value="@Model[b, a]" placeholder="" @(b < currentMonth ? "readonly" : "") />
                                    <span class="input-group-addon">%</span>
                                }
                                else
                                {
                                    <span class="input-group-addon">$</span>
                                    <input type="text" class="form-control" name="model[@b][@a]" id="model[@b][@a]" value="@Model[b, a]" placeholder="" @(b < currentMonth ? "readonly" : "") />
                                }
                            </div>
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            @Html.ValidationSummary()
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button type="button" class="btn btn-default" onclick="window.location.href = '/BenefitProgramsManagement/Coupon/PromotionsDetail';">Cancelar</button>
        </div>
    </div>
}
@section pageCSS{
}
@section pageScripts{
    <script type="text/javascript">
        function ValidateForm() {
            return true;
        }
    </script>
}