PSD.Web/Areas/Content/Models/ContactPageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PSD.Web.Areas.Content.Models
{
    public class ContactPageViewModel
    {
        public string Name { get; set; }
        public string EMail { get; set; }
        public string Message { get; set; }
    }
}

PSD.Web/Areas/Content/Controllers/ContactPageController.cs
using PSD.Web.Areas.Content.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PSD.Web.Areas.Content.Controllers
{
    public class ContactPageController : PSD.Web.Controllers._BaseWebController
    {
        private Controller.Content.ContentDataController controller;
        public ContactPageController()
            : base("ContactPageController")
        {
            controller = new Controller.Content.ContentDataController(Configurations);
        }
        // GET: Content/ContactPage
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ContactPageViewModel model = new ContactPageViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactPageViewModel model)
        {
            if (controller.SendContactMail(model.Name, model.EMail, model.Message) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return View(model);
        }
    }
}

PSD.Web/Areas/ContentManagement/Controllers/ContactPageController.cs
using PSD.Model;
using PSD.Security;
using PSD.Web.Areas.ContentManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PSD.Web.Areas.ContentManagement.Controllers
{
    [Authorization(allowedRoles: "appadmin")]
    public class ContactPageController : PSD.Web.Controllers._BaseWebController
    {
        private Controller.Content.ContentDataController controller;
        public ContactPageController()
            : base("ContactPageController")
        {
            controller = new Controller.Content.ContentDataController(Configurations);
        }

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult ContactPageUpdate()
        {
            var key = Controller.Content.ContentTypeKey.ContactPageContent;
            ContentData itemToEdit = controller.GetContentDataByKey(key);
            UpdateHtmlContentViewModel model = new UpdateHtmlContentViewModel()
            {
                Content = HttpUtility.HtmlDecode(itemToEdit != null ? itemToEdit.Value : "<p><br></p>")
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ContactPageUpdate(UpdateHtmlContentViewModel model)
        {
            var jumbotronTextKey = Controller.Content.ContentTypeKey.ContactPageContent;

            string encodedContent = HttpUtility.HtmlEncode(model.Content);

            if (controller.Update(jumbotronTextKey, encodedContent) || controller.ResultManager.IsCorrect)
            {
                NotifyUser(messageOk: "Contenido texto para pagina de contacto editado correctamente");
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return View(model);
        }
    }
}

PSD.Web/Areas/Content/Views/ContactPage/Contact.cshtml
@model PSD.Web.Areas.Content.Models.ContactPageViewModel
@{
    ViewBag.Title = "Contacto";
}

@using (Html.BeginForm("Contact", "ContactPage", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal col-md-10", role = "form", onsubmit = "return ValidateForm()", name = "Create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();

    <div class="form-group" id="grp">
        <div class="col-md-6 col-md-offset-3">
            @{var content = PSD.Web.Controllers._BaseWebController.GetContactPageContent();}
            @Html.Raw(content)
        </div>
    </div>

    <div class="form-group" id="grp">
        <div class="col-md-6 col-md-offset-3">
            <input type="text"
                   class="form-control"
                   name="Name"
                   id="Name"
                   value="@Model.Name"
                   placeholder="Nombre"
                   required
                   oninvalid="this.setCustomValidity('Por favor ingresa tu nombre')"
                   oninput="setCustomValidity('')" />
        </div>
    </div>

    <div class="form-group" id="grp">
        <div class="col-md-6 col-md-offset-3">
            <input type="email"
                   class="form-control"
                   name="EMail"
                   id="EMail"
                   value="@Model.EMail"
                   placeholder="Email"
                   required
                   oninvalid="this.setCustomValidity('Por favor ingresa una direccion de E-mail valida')"
                   oninput="setCustomValidity('')" />
        </div>
    </div>

    <div class="form-group" id="grp">
        <div class="col-md-6 col-md-offset-3">
            <textarea type="text"
                   class="form-control"
                   name="Message"
                   id="Message"
                   value="@Model.Message"
                   placeholder="Mensaje"
                   required
                   oninvalid="this.setCustomValidity('Por favor ingresa un mensaje')"
                   oninput="setCustomValidity('')">
            </textarea>
        </div>
    </div>
    <div class="form-group" id="grp">
        <div class="col-md-6 col-md-offset-3">
            <input type="checkbox" required name="terms"> Acepto los <a><span class="text-primary cursor-link">Terminos y Condiciones</span></a>
        </div>
        <div class="col-md-6 col-md-offset-3">
            <input type="checkbox" required name="privacy"> Acepto el <a><span class="text-primary cursor-link">Aviso de privacidad</span></a>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-6 col-md-offset-3">
            @Html.ValidationSummary()
            <button type="submit" class="btn btn-primary col-md-12">Enviar</button>
            @*<button type="button" class="btn btn-default" onclick="window.location='/';">Cancelar</button>*@
        </div>
    </div>
}

@section pageScripts{
    <script type="text/javascript">
        function ValidateForm() {
            return true;
        }
    </script>
}