PSD.Web/Areas/Content/Models/DetailViewModel.cs
using PSD.Model;

namespace PSD.Web.Areas.Content.Models
{
    public class DetailViewModel
    {
        public News DetailNews { get; set; }
        public News PreviousNews { get; set; }
        public News NextNews { get; set; }
    }
}

PSD.Web/Areas/Contracts/Controllers/BayerToDistributorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PSD.Model;
using PSD.Security;

namespace PSD.Web.Areas.Contracts.Controllers
{
    [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeManagerView + "," + Controller.UserRole.EmployeeRTVOperation + "," + Controller.UserRole.EmployeeRTVView)]
    public class BayerToDistributorController : PSD.Web.Controllers._BaseWebController
    {
        private Controller.Contracts.ContractsDistributorController controller;
        public BayerToDistributorController()
            : base("BayerToDistributorController")
        {
            controller = new Controller.Contracts.ContractsDistributorController(Configurations);
        }


        public ActionResult Index()
        {
            List<ContractDistributor> items = controller.FilteredItems();
            if (controller.ResultManager.IsCorrect)
            {
                return View(items);
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Index");
        }

        public ActionResult Detail(int Id = -1)
        {
            //sys validations
            if (Id == -1)
            {
                NotifyUser(errorDefault, controllerTraceId + "Detail.111 No se recibió el parámetro Id");
                return RedirectToAction("Index");
            }

            ContractDistributor item = controller.Retrieve(Id);
            if (item != null && controller.ResultManager.IsCorrect)
            {
                return View(item);
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Index");
        }

        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Create(int Id = -1)
        {
            //sys validations
            if(Id == -1)
            {
                NotifyUser(errorDefault, controllerTraceId + "Create.111 No se recibió el parámetro id del Distribuidor");
                return RedirectToAction("Index");
            }

            ContractDistributor item = ContractDistributor.NewEmpty();
            PSD.Controller.DistributorController distributorController = new Controller.DistributorController(Configurations);
            item.Distributor = distributorController.RetrieveDistributor(Id);
            item.DistributorId = Id;
            item.RegisteredZoneName = item.Distributor.Address.AddressColony.AddressPostalCode.AddressMunicipality.Zone.Name;
            item.RegisteredRegionName = item.Distributor.Address.AddressColony.AddressPostalCode.AddressMunicipality.Zone.RegionName;

            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Create(ContractDistributor model)
        {                
            if (controller.Create(model, true) || controller.ResultManager.IsCorrect)
            {
                NotifyUser(messageOk: "Contracto creado correctamente");
                return RedirectToAction("Index");
            }

            PSD.Controller.DistributorController distributorController = new PSD.Controller.DistributorController(Configurations);
            model.Distributor = distributorController.RetrieveDistributor(model.DistributorId);
            
            NotifyUser(resultManager: controller.ResultManager);
            return View(model);
        }

        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Edit(int Id)
        {
            ContractDistributor itemToEdit = controller.Retrieve(Id);
            if (controller.ResultManager.IsCorrect)
            {
                return View(itemToEdit);
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Edit(ContractDistributor model, string postAction = "")
        {
            if (model == null)
            {
                return RedirectToError(messageDebug: controllerTraceId + "DistributorCreate[Post].111 No model was received");
            }

            bool sendToDistributorReview = false;
            switch (postAction)
            {
                case "updateOnly": sendToDistributorReview = false; break;
                case "updateAndSendToDistributor": sendToDistributorReview = true; break;
            }
            if (controller.Update(model, sendToDistributorReview) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(messageOk: controller.ResultManager.ToDescriptionString(), messageDebug: controllerTraceId + "Edit.831 Contrato '[" + model.Id + "]:" + model.IdB + "' actualizado");
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return View(model);
        }
        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Approve(int Id)
        {
            ContractDistributor item = controller.Retrieve(Id);
            if (!controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("Index");
            }

            if(item.AmountGoalTotal < item.AmountGoalTotalPre)//amount indicated by distributor is less than the indicated by bayer?
            {//yes
                //validate approver is GRV, RTV cannot approve on this case
                if(!Identity.CurrentUser.IsInRole(PSD.Controller.UserRole.AppAdmin + "," +  PSD.Controller.UserRole.EmployeeManagerOperation))
                {
                    NotifyUser(messageError: "Los montos indicados por el Distribuidor son menores, se necesita aprobación de GRV");
                    return RedirectToAction("Detail", new { Id = Id });
                }
            }

            if (controller.Approve(item) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(messageOk: controller.ResultManager.ToDescriptionString(), messageDebug: controllerTraceId + "Approve.831 Contrato '[" + item.Id + "]:" + item.IdB + "' actualizado");
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Detail", new { Id = Id });
        }
        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult RequestApprovalDistributor(int Id)
        {
            if (controller.SendToDistributor(Id) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Detail", new { Id = Id });
        }
        [Authorization(allowedRoles: Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult RequestApprovalGRV(int Id)
        {
            if (controller.RequestApprovalGRV(Id) && controller.ResultManager.IsCorrect)
            {
                NotifyUser(resultManager: controller.ResultManager);
                return RedirectToAction("Index");
            }

            NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Detail", new { Id = Id });
        }

        [Authorization(allowedRoles: Controller.UserRole.AppAdmin + "," + Controller.UserRole.EmployeeManagerOperation + "," + Controller.UserRole.EmployeeRTVOperation)]
        public ActionResult Delete(int Id)
        {
            if (controller.Delete(Id) || controller.ResultManager.IsCorrect)
                NotifyUser(messageOk: "Convenio con distribuidor eliminado correctamente");
            else
                NotifyUser(resultManager: controller.ResultManager);
            return RedirectToAction("Index");
        }
    }
}

PSD.Web/Areas/Contracts/Views/BayerToDistributor/Create.cshtml
@using PSD.Model
@using PSD.Security
@model PSD.Model.ContractDistributor
@{
    ViewBag.Title = "Alta de Convenio Bayer-Distribuidor";
    int currentMonth = PSD.Common.Dates.Today.Month;
}

@using (Html.BeginForm("Create", "BayerToDistributor", new { returnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal col-md-10", role = "form", onsubmit = "return ValidateForm()", name = "Create" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.DistributorId)
    <!--
    <div class="form-group" id="grpDistributor.CropId">
        <label for="Distributor.CropId" class="col-md-4 control-label">Productos <span id="_lblDistributor.CropId" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Volumen</th>
                        <th>Unidad</th>
                    </tr>
                </thead>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </table>
        </div>
        <div class="col-md-8 col-md-offset-4">
            <select name="selectedAddressState" id="selectedAddressState" class="form-control multiselect" onchange="">
                <option value="-1">Seleccionar...</option>
                <option value="-1">Producto1</option>
                <option value="-1">Producto2</option>
                <option value="-1">Producto3</option>
                <option value="-1">Producto4</option>
            </select>
            <input type="text" class="form-control col-md-2" name="IdB" id="IdB" value="" placeholder="Volumen" />
            <select name="selectedCrops" id="selectedCrops" class="form-control multiselect ">
                <option value="-1">Seleccionar...</option>
                <option value="-1">Litros</option>
                <option value="-1">Kilogramos</option>
                <option value="-1">Piezas</option>
            </select>
            <button type="button" class="btn btn-warning" onclick="Create.postAction.value = 'addInfluence'; Create.submit();" disabled>agregar</button>
        </div>
    </div>
    -->
    <div class="form-group" id="grpYear">
        <label for="Year" class="col-md-4 control-label">Año<span id="_lblYear" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            <input type="text" class="form-control" name="Year" id="Year" value="@Model.Year" placeholder="" readonly />
        </div>
    </div>
    <div class="form-group" id="grpDistributor.CommercialName">
        <label for="Distributor.CommercialName" class="col-md-4 control-label">Distribuidor<span id="_lblDistributor.CommercialName" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            <input type="text" class="form-control" name="Distributor.CommercialName" id="Distributor.CommercialName" value="@Model.Distributor.CommercialName" placeholder="" readonly />
        </div>
    </div>
    <div class="form-group" id="grpRegisteredZoneName">
        <label for="RegisteredZoneName" class="col-md-4 control-label">Regi&oacute;n registrada<span id="_lblRegisteredZoneName" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            <input type="text" class="form-control" name="RegisteredRegionName" id="RegisteredRegionName" value="@Model.RegisteredRegionName" placeholder="" readonly />
        </div>
    </div>
    <div class="form-group" id="grpRegisteredZoneName">
        <label for="RegisteredZoneName" class="col-md-4 control-label">Zona registrada<span id="_lblRegisteredZoneName" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            @*<select name="selectedAddressState" id="selectedAddressState" class="multiselect" onchange="">
                    <option value="-1">Seleccionar...</option>
                    @foreach (SelectListItem item in new LinkedList<SelectListItem>())
                    {
                        <option value="@item.Value" @(item.Selected ? "selected" : "")>@item.Text</option>
                    }
                </select>*@
            <input type="text" class="form-control" name="RegisteredZoneName" id="RegisteredZoneName" value="@Model.RegisteredZoneName" placeholder="" readonly />
        </div>
    </div>
    <div class="form-group" id="">
        <label for="" class="col-md-4 control-label">Meta<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-6">
            <table class="table table-condensed text-center">
                <thead>
                    <tr>
                        <th class="text-center">Periodo</th>
                        <th class="text-center">Valor Bayer</th>
                    </tr>
                </thead>
                <tr>
                    <td>
                        <label for="IdB" class="control-label">Q1<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                    </td>
                    <td>
                        <div class="input-group col-md-9">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="AmountGoalQ1Pre" id="AmountGoalQ1Pre" value="@(Model.AmountGoalQ1Pre>0? Model.AmountGoalQ1Pre.ToString() : "0")" placeholder="" onchange="CalculateTotal()" tabindex="1" @(currentMonth > 3 ? "readonly" : "") />
                            <span class="input-group-addon">MXN</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="IdB" class="control-label">Q2<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                    </td>
                    <td>
                        <div class="input-group col-md-9">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="AmountGoalQ2Pre" id="AmountGoalQ2Pre" value="@(Model.AmountGoalQ2Pre>0? Model.AmountGoalQ2Pre.ToString() : "0")" placeholder="" onchange="CalculateTotal()" tabindex="2" @(currentMonth > 6 ? "readonly" : "") />
                            <span class="input-group-addon">MXN</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="IdB" class="control-label">Q3<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                    </td>
                    <td>
                        <div class="input-group col-md-9">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="AmountGoalQ3Pre" id="AmountGoalQ3Pre" value="@(Model.AmountGoalQ3Pre>0? Model.AmountGoalQ3Pre.ToString() : "0")" placeholder="" onchange="CalculateTotal()" tabindex="3" @(currentMonth > 9 ? "readonly" : "") />
                            <span class="input-group-addon">MXN</span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <label for="IdB" class="control-label">Q4<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                    </td>
                    <td>
                        <div class="input-group col-md-9">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control" name="AmountGoalQ4Pre" id="AmountGoalQ4Pre" value="@(Model.AmountGoalQ4Pre>0? Model.AmountGoalQ4Pre.ToString() : "")" placeholder="" onchange="CalculateTotal()" tabindex="4" />
                            <span class="input-group-addon">MXN</span>
                        </div>
                    </td>
                </tr>
                <tfoot>
                    <tr>
                        <td><label for="IdB" class="col-md-4 control-label">Meta<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label></td>
                        <td>
                            <div class="input-group col-md-9">
                                <span class="input-group-addon">$</span>
                                <input type="text" class="form-control" name="AmountGoalTotalPre" id="AmountGoalTotalPre" value="@(Model.AmountGoalTotalPre > 0 ? Model.AmountGoalTotalPre.ToString() : "")" placeholder="" readonly />
                                <span class="input-group-addon">MXN</span>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
@*    <div class="form-group" id="grpGRVBayerEmployeeId">
        <label for="GRVBayerEmployeeId" class="col-md-4 control-label">GRV asignado <span id="_lblGRVBayerEmployeeId" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            <select name="GRVBayerEmployeeId" id="GRVBayerEmployeeId" class="multiselect" onchange="" readonly>
                @foreach (SelectListItem item in PSD.Web.Controllers._BaseWebController.Grvs())
                {
                    <option value="@item.Value" @(item.Value == Model.GRVBayerEmployeeId.ToString() ? "selected" : "")>@item.Text</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group" id="grpRTVBayerEmployeeId">
        <label for="RTVBayerEmployeeId" class="col-md-4 control-label">RTV asignado <span id="_lblRTVBayerEmployeeId" class="field-validation-error text-danger" style="display:none;"></span></label>
        <div class="col-md-8">
            @if (Identity.CurrentUser.IsInRole("employee-rtv_operation"))
            {
                <input type="text" class="form-control" name="" id="" value="@Identity.CurrentUser.DisplayName" readonly />
                <input type="hidden" id="RTVBayerEmployeeId" name="RTVBayerEmployeeId" value="@Identity.CurrentUser.Id" />
            }
            else
            {<select name="RTVBayerEmployeeId" id="RTVBayerEmployeeId" class="multiselect" onchange="">
                    <option value="-1">Seleccionar...</option>
                    @foreach (SelectListItem item in PSD.Web.Controllers._BaseWebController.Rtvs())
                {
                        <option value="@item.Value" @(item.Value == Model.RTVBayerEmployeeId.ToString() ? "selected" : "")>@item.Text</option>
                }
                </select>
            }
        </div>
    </div>
*@
    <div class="form-group">
        <div class="col-md-10 col-md-offset-4">
            @Html.ValidationSummary()
            <button type="submit" class="btn btn-primary">Crear convenio</button>
            <button type="button" class="btn btn-default" onclick="window.location='/';">Cancelar</button>
        </div>
    </div>
}
@section pageCSS{
}
@section pageScripts{
    <script type="text/javascript">
        function ValidateForm() {
            return true;
        }
        function CalculateTotal() {
            var q1 = parseFloat(0 + $("#AmountGoalQ1Pre").val());
            var q2 = parseFloat(0 + $("#AmountGoalQ2Pre").val());
            var q3 = parseFloat(0 + $("#AmountGoalQ3Pre").val());
            var q4 = parseFloat(0 + $("#AmountGoalQ4Pre").val());
            $("#AmountGoalTotalPre").val(q1 + q2 + q3 + q4);
        }

    </script>
}

PSD.Web/Areas/Contracts/Views/BayerToDistributor/Detail.cshtml
@using PSD.Security
@using PSD.Model
@using PSD.Common
@using PSD.Controller
@model PSD.Model.ContractDistributor
@{
    ViewBag.Title = "Detalle de convenio Bayer-Distribuidor";
    ViewBag.SubTitle = Model.IdB;
}

<div class="row">
    <div class="col-md-8">
        <div class="form-group">
            <label for="Folio" class="col-md-4 control-label">Id</label>
            <div class="col-md-8">
                <p class="form-control">@Model.IdB</p>
            </div>
        </div>
        <div class="form-group">
            <label for="Folio" class="col-md-4 control-label">Estatus</label>
            <div class="col-md-8">
                <p class="form-control">@Model.ContractDistributorStatus.Name</p>
            </div>
        </div>
        <div class="form-group" id="grpYear">
            <label for="Year" class="col-md-4 control-label">Año<span id="_lblYear" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <p class="form-control">@Model.Year</p>
            </div>
        </div>
        <div class="form-group" id="grpYear">
            <label for="Year" class="col-md-4 control-label">Fecha de convenio<span id="_lblYear" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <p class="form-control">@PSD.Common.Strings.FormatDate(Model.ContractDate)</p>
            </div>
        </div>
        <div class="form-group" id="grpDistributor.CommercialName">
            <label for="Distributor.CommercialName" class="col-md-4 control-label">Distribuidor<span id="_lblDistributor.CommercialName" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <p class="form-control">@Model.Distributor.CommercialName</p>
            </div>
        </div>
        <div class="form-group">
            <label for="RegisteredZoneName" class="col-md-4 control-label">Regi&oacute;n registrada<span id="_lblRegisteredZoneName" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <p class="form-control">@Model.RegisteredRegionName</p>
            </div>
        </div>
        <div class="form-group">
            <label for="RegisteredZoneName" class="col-md-4 control-label">Zona registrada<span id="_lblRegisteredZoneName" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <p class="form-control">@Model.RegisteredZoneName</p>
            </div>
        </div>
        <div class="form-group" id="">
            <label for="" class="col-md-4 control-label">Meta<span id="_lbl" class="field-validation-error text-danger" style="display:none;"></span></label>
            <div class="col-md-8">
                <table class="table table-condensed text-center">
                    <thead>
                        <tr>
                            <th class="text-center">Periodo</th>
                            <th class="text-center">Meta Bayer</th>
                            <th class="text-center">Meta Distribuidor</th>
                        </tr>
                    </thead>
                    <tr>
                        <td>
                            <label for="IdB" class="control-label">Q1<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p>@Strings.FormatCurrency(@Model.AmountGoalQ1Pre, true, true)</p>
                            </div>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ1, true, true)</p>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="IdB" class="control-label">Q2<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ2Pre, true, true)</p>
                            </div>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ2, true, true)</p>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="IdB" class="control-label">Q3<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ3Pre, true, true)</p>
                            </div>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ3, true, true)</p>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="IdB" class="control-label">Q4<span id="_lblIdB" class="field-validation-error text-danger" style="display:none;"></span></label>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ4Pre, true, true)</p>
                            </div>
                        </td>
                        <td>
                            <div class="input-group col-md-6">
                                <p class="">@Strings.FormatCurrency(@Model.AmountGoalQ4, true, true)</p>
                            </div>
                        </td>
                    </tr>
                    <tfoot>
                        <tr>
                            <td><label for="" class="text-primary">Meta</label></td>
                            <td>
                                <div class="input-group col-md-6">
                                    <p class="text-primary">@Strings.FormatCurrency(@Model.AmountGoalTotalPre, true, true)</p>
                                </div>
                            </td>
                            <td>
                                <div class="input-group col-md-6">
                                    <p class="text-primary">@PSD.Common.Strings.FormatCurrency(@Model.AmountGoalTotal, true, true)</p>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        @*
            <div class="form-group" id="grpNickName">
                <label for="GRVBayerEmployeeId" class="col-md-4 control-label">GRV asignado <span id="_lblGRVBayerEmployeeId" class="field-validation-error text-danger" style="display:none;"></span></label>
                <div class="col-md-8">
                    <p class="form-control">@Model.GRVBayerEmployee.NameDisplay</p>
                </div>
            </div>
            <div class="form-group" id="grpRTVBayerEmployeeId">
                <label for="RTVBayerEmployeeId" class="col-md-4 control-label">RTV asignado <span id="_lblRTVBayerEmployeeId" class="field-validation-error text-danger" style="display:none;"></span></label>
                <div class="col-md-8">
                    <p class="form-control">@Model.RTVBayerEmployee.NameDisplay</p>
                </div>
            </div>
        *@
        <div class="form-group">
            <label for="Folio" class="col-md-4 control-label"></label>
            <div class="col-md-6">
                @if (Model.ContractDistributorStatus.IdB == "review-bayer")
                {
                    if (Identity.CurrentUser.IsInRole(UserRole.EmployeeManagerOperation))
                    {
                        <button type="button" class="btn btn-primary" onclick="window.location = '/Contracts/BayerToDistributor/Approve/@Model.Id';">Aprobar</button>
                    }
                    if (Identity.CurrentUser.IsInRole(UserRole.EmployeeRTVOperation))
                    {
                        <button type="button" class="btn btn-primary" onclick="window.location = '/Contracts/BayerToDistributor/RequestApprovalDistributor/@Model.Id';">Enviar a revisi&oacute;n distribuidor</button>
                        <button type="button" class="btn btn-info" onclick="window.location = '/Contracts/BayerToDistributor/RequestApprovalGRV/@Model.Id';">Solicitar aprobaci&oacute;n GRV</button>
                        <button type="button" class="btn btn-info" onclick="window.location = '/Contracts/BayerToDistributor/Edit/@Model.Id';">Editar</button>
                        if (Model.Distributor.CurrentContract == null)
                        {//no tiene ningun convenio
                            <button type="button" class="btn btn-info" onclick="window.location.href = '/Contracts/BayerToDistributor/Create/@Model.Id';">Crear convenio</button>
                        }
                    }
                }
                <button type="button" class="btn btn-default" onclick="window.location = '/Contracts/BayerToDistributor';">Regresar</button>
            </div>
            <div class="col-md-2 text-right">
                @if (Identity.CurrentUser.IsInRole(UserRole.EmployeeManagerOperation + "," + UserRole.EmployeeRTVOperation))
                {
                    <button type="button" class="btn btn-danger" onclick='if (confirm(" ¿está seguro de que desea eliminar este convenio?")) window.location.href = "/Contracts/BayerToDistributor/Delete/@Model.Id" ;'>Eliminar</button>
                }
            </div>
        </div>
    </div>
</div>

@section pageCSS{
}
@section pageScripts{
}